### PR TITLE
Resolve lineheight units warning

### LINKED ISSUE #143: WARN  Expected style "lineHeight: 16" to contain units
### What brings you here and how are you?

Nothing particular on this warm and hot day in stockholm 🥵

### Description

Styled lib warns about `lineHeight` not including a unit.
image

### Steps to Reproduce

Shows on first app start

### PR DESCRIPTION
**Pull request by kajsaunge**
Removes usage of stylesheet create where possible
Removes style objects to use styled components 

Adds px units for lineheight to get rid of units warning

Closes #143 #104

### CODE REVIEW

**Review by gewfy — APPROVED** [review]

File: client/src/common/components/Typography/styles.ts [hunk 1]
```diff
@@ -38,6 +38,7 @@ export default StyleSheet.create({
     color: COLORS.GREY,
     fontSize: 20,
     lineHeight: 26,
+    padding: 1,
```
Comment (gewfy) [inline client/src/common/components/Typography/styles.ts:41]: Is this correct @kajsaunge ?

File: client/src/lib/uiLib/components/DrawerMenu.tsx [hunk 2]
```diff
@@ -1,43 +1,40 @@
...
-    fontSize: 15,
-    paddingLeft: 40,
-    color: 'black',
-  },
-  menuItemTextActive: {
-    color: 'white',
-  },
+const SafeAreaViewWrapper = styled(SafeAreaView)({flex: 1});
+
+const ScrollViewWrapper = styled(ScrollView)({flex: 1});
```
Comment (gewfy) [inline client/src/lib/uiLib/components/DrawerMenu.tsx:21]: You actually don't need to import components from `react-native`. Here you can instead write `styled.ScrollView({flex: 1});`

File: client/src/common/components/Typography/styles.ts (hunk 1 above)
Comment (kajsaunge) [reply client/src/common/components/Typography/styles.ts:41]: Oh thanks, I'll remove it 😬
